// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAenXW-mALmuGmX9ZDJCnuZVVpj2pCv7I4',
    appId: '1:756695116736:web:5b71cb4e1b0920bb5b3625',
    messagingSenderId: '756695116736',
    projectId: 'resqnet-7578d',
    authDomain: 'resqnet-7578d.firebaseapp.com',
    storageBucket: 'resqnet-7578d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOy6wsSD7Pmb6nKnKNlxWxGLtQAHsdcyM',
    appId: '1:756695116736:android:97f93ecd74a419dd5b3625',
    messagingSenderId: '756695116736',
    projectId: 'resqnet-7578d',
    storageBucket: 'resqnet-7578d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykLF8IaFbnELUG14J2lUSp-IehC9JDis',
    appId: '1:756695116736:ios:ba74193e605765385b3625',
    messagingSenderId: '756695116736',
    projectId: 'resqnet-7578d',
    storageBucket: 'resqnet-7578d.firebasestorage.app',
    iosBundleId: 'com.example.smartEmergencyResponse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykLF8IaFbnELUG14J2lUSp-IehC9JDis',
    appId: '1:756695116736:ios:ba74193e605765385b3625',
    messagingSenderId: '756695116736',
    projectId: 'resqnet-7578d',
    storageBucket: 'resqnet-7578d.firebasestorage.app',
    iosBundleId: 'com.example.smartEmergencyResponse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAenXW-mALmuGmX9ZDJCnuZVVpj2pCv7I4',
    appId: '1:756695116736:web:4a271e6d776b907d5b3625',
    messagingSenderId: '756695116736',
    projectId: 'resqnet-7578d',
    authDomain: 'resqnet-7578d.firebaseapp.com',
    storageBucket: 'resqnet-7578d.firebasestorage.app',
  );
}
